version: '3.8'
name: ${LLAMANATOR_COMPOSE_GROUP_NAME:-highsideai-stack}
services:
  ollama:
    image: ollama/ollama:${OLLAMA_IMAGE_VERSION}
    container_name: ollama
    volumes:
      - ./ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=${OLLAMA_ORIGINS}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL}
      - OLLAMA_MAX_VRAM=${OLLAMA_MAX_VRAM}
      - OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS}
    ports:
      - "${OLLAMA_PORT}:11434"
    restart: unless-stopped
